language: php

php:
  - 8.1

os: linux

services:
  - postgresql
  - redis

before_install:
  - phpenv config-rm xdebug.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - psql -c 'create database iati_db_test;' -U postgres
  - php artisan migrate --seed
  - php artisan config:clear
