language: php

php:
  - 8.0
  - 8.1

os: linux

services:
  - postgresql

before_script: 
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - cp .env.example .env
  - php artisan key:generate
  - psql -c 'create database iati_db_test;' -U postgres
  - php artisan migrate --seed
