<?php

return [
    'add_a_title_and_identifier_for_the_activity'                                       => 'Añada un título y un identificador a la actividad',
    'a_code_specifying_the_language_of_text_in_this_element'                            => 'Podrá añadir títulos en otros idiomas después de haber creado la actividad.',
    'a_globally_unique_identifier_for_the_activity'                                     => 'Identificador único de la actividad. Una vez publicada una actividad de la IATI, no se podrá cambiar su identificador en actualizaciones posteriores.',
    'type_activity_identifier_here'                                                     => 'Escribir el indicador aquí',
    'enter_your_own_unique_activity_identifier_such_as_abbreviation_or_simply_a_number' => 'Introduzca una cadena de caracteres, como una abreviatura o un número, para asignar un identificador único a esta actividad. IATI Publisher lo combinará con su identificador de la organización para crear el "iati-identifier" (identificador de la IATI) de esta actividad.',
    'this_is_autogenerated'                                                             => 'Se genera automáticamente.',
];
