apiVersion: apps/v1
kind: Deployment
metadata:
  name: iatipublisher-fpm
  labels:
    tier: backend
    layer: fpm
spec:
  selector:
    matchLabels:
      tier: backend
      layer: fpm
  replicas: 1
  template:
    metadata:
      labels:
        tier: backend
        layer: fpm
    spec:
      serviceAccountName: iatipublisher
      imagePullSecrets:
        - name: github-credentials
      initContainers:
        - name: migrations
          image: ghcr.io/IATI/iatipublisher/cli
          command: [ "/bin/sh","-c" ]
          args: ["chown -R www-data:www-data /opt/apps/laravel-in-kubernetes/storage/logs; php artisan migrate --force"]
          volumeMounts:
          - name: iati-persistent-storage
            mountPath: /opt/apps/laravel-in-kubernetes/storage/logs
          envFrom:
            - configMapRef:
                name: iatipublisher
            - secretRef:
                name: iatipublisher
      containers:
      - name: iatipublisher-fpm
        envFrom:
          - configMapRef:
              name: iatipublisher
          - secretRef:
              name: iatipublisher
        image: ghcr.io/IATI/iatipublisher/fpm_server
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sh","-c" ]
        args: ["php artisan optimize:clear && php artisan command:UpdateJsonFiles && php artisan command:SetAppDataJsonCache && php artisan command:FetchOrganisationRegistrationAgency; php-fpm"]
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: iati-persistent-storage
          mountPath: /opt/apps/laravel-in-kubernetes/storage/logs
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
      volumes:
      - name: iati-persistent-storage
        persistentVolumeClaim:
          claimName: iati-pv-claim
