apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- common/service-account.yaml
- fpm/deployment.yaml
- fpm/service.yaml
- cron/cronjob.yaml
- cron/clear-laravel-logs.yaml
# - cron/custom-command-cron.yaml
- queue-workers/deployment.yaml
- webserver/deployment.yaml
- webserver/service.yaml
# - cron/fix-storage-permission.yaml
# !todo uncomment them
