apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- common/service-account.yaml
- cron/cronjob.yaml
- fpm/deployment.yaml
- fpm/service.yaml
- queue-workers/deployment.yaml
- webserver/deployment.yaml
- webserver/service.yaml
