apiVersion: batch/v1
kind: CronJob
metadata:
  name: clear-laravel-logs
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clear-laravel-logs
            image: ghcr.io/younginnovations/iatipublisher/cli
            command: ["/bin/sh"]
            args:
              - "-c"
              - |
                find /opt/apps/laravel-in-kubernetes/storage/logs -type f -mtime +10 -exec rm {} \;
            volumeMounts:
            - name: iati-persistent-storage
              mountPath: /opt/apps/laravel-in-kubernetes/storage/logs
          restartPolicy: OnFailure
