apiVersion: batch/v1
kind: CronJob
metadata:
  name: iati-custom-command-cron
  labels:
    tier: backend
    layer: cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: iatipublisher
          imagePullSecrets:
            - name: github-credentials
          containers:
          - name: iati-custom-command-cron
            image: ghcr.io/younginnovations/iatipublisher/cron
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - php artisan schedule:run
            envFrom:
              - configMapRef:
                  name: iatipublisher
              - secretRef:
                  name: iatipublisher
          restartPolicy: OnFailure
