apiVersion: batch/v1
kind: CronJob
metadata:
  name: iati-fix-storage-permission
  labels:
    tier: backend
    layer: cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: iatipublisher
          imagePullSecrets:
            - name: github-credentials
          containers:
          - name: iati-fix-storage-permission
            image: ghcr.io/IATI/iatipublisher/cli
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - chown -R www-data:www-data /opt/apps/laravel-in-kubernetes/storage/logs
            envFrom:
              - configMapRef:
                  name: iatipublisher
              - secretRef:
                  name: iatipublisher
            volumeMounts:
            - name: iati-persistent-storage
              mountPath: /opt/apps/laravel-in-kubernetes/storage/logs
          restartPolicy: OnFailure
          volumes:
          - name: iati-persistent-storage
            persistentVolumeClaim:
              claimName: iati-pv-claim
