apiVersion: batch/v1
kind: CronJob
metadata:
  name: kill-idle-postgres-connections
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: psql
              image: postgres
              command:
                - sh
                - -c
                - |
                  PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -d $DB_DATABASE -U $DB_USERNAME -p $DB_PORT -c " SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE  pid <> pg_backend_pid()
                  AND state in ('idle', 'idle in transaction', 'idle in transaction (aborted)', 'disabled')
                  AND state_change < current_timestamp - INTERVAL '1' MINUTE;"
              envFrom:
                - configMapRef:
                    name: iatipublisher
                - secretRef:
                    name: iatipublisher
          restartPolicy: OnFailure
