apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-credentials
  namespace: iati-production
spec:
  encryptedData:
    .dockerconfigjson: AgAZOMOEPwG7itB3TFH6xmrpDW5JfvWTx8rm1UZZGHaT+soyI5UeWRpvitENrDppgynh6o+BZIPlY2oG3x7Ymg19wPvcjFKv5TxBjk5iGvbMYyHvTJWmIZvLYR+A+GCPiaXCpn7i3a2ewrPDdyReymaIgICIAt0ntDuaF23otDTzEN73uc+JNPAZ/KnjPzGnmUD0XY5qOr4jr1FZhxO8uOHRtK7pfH2bBBPpZgLCmdbRZkM1JdorK6j7GGecePert4lpIEWmvLP0JC/y1P7/dz9obTwTyq/g6b5nzIcHXVndr0WrTtZxHp3OKciPn6EsTmri3gfk41YyIBD3GuZ7GZd/ksWBUKcSvSM7ZCYlvneILDyN4uxmrcY0tBM9GW0G6FMLVhk7oK+dcuawi9W45BQwbYEF1H3XHSDwwV1qaMIBGsM6ietR2MGXua+UpMBaWKGVpYUjm5oaRPDVrTJwSgHOK7wjlWDqloxY7XXoz16uiFPeIsJwUbMEvbeubU9Gnfr6uCJwXF55xPekz0J6ZL8msC5/mA3e79e+IUR2dZtUO1U2QWhx1wCHS+iYtcgKZ6McDRE418Ioi5QoQOg2Yw5euBqdeUOtMO0I3+gb64m2/ZAEOOKFmgB+rN68QcTl8ywg0zYzRpluHRK3LuKnj9h1xPNyqrXtykCjQOaaCICpjLH+gRoDMNapXz8yQBndf9x0g+CRzj/r3ORXIAKdm9vgBGaq8WtMPGrbiYykzDJkfjh3gSTSIB1BETy2K6l2U1VadadiHxGzp9/KhCPgn+j3Wy9ZUyipArRCekF0DUbm8TbA4dk8A9emssiCHvnL3VMWZ7k1Ka1e1wc=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-credentials
      namespace: iati-production
    type: Opaque

