apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-credentials
  namespace: iati-production
spec:
  encryptedData:
    .dockerconfigjson: AgDaIZLzVpUuNtke2B6Qk3Dhe2T/Io4MZbQP9pLLzd6il8LJvMJiA7v7HV2KLeczofhbLF4Es2aVgj0KGP43n2X7b5C+iyztR/JXaUV4IlsFUxGylaS5+A2xYzxtR9ziGRuUyxKnW5btJdJ/zY1H1zwIwL7AXSqdJ+fnZ7sj6OkvLznA2Nu6P5J1/CcHG8Z4ar4TWck4g5vAaa/oFvuWz4JETGbsvy8WNcien1qAX/jfikybUrPntYJe4clvND9Al7SiL0w+Na1a2NN6vmFOsEgSwAnNSDBfWPjwMdAdiFlsqep+SLV1C9FrIu5SS6QqQmWuSoI4v6R7MHsxlMZEO3VdjcAx0mbRDORKab2WFLs67UXhdB6sYd+TxufKej6h+n/tYYcoGMyJJKK1sgHbifq/VvavHXYw7npFrwG8qkO5rch1Pbfbrn4PoWm76be7Y5Joeq2eA1gCR2oC1bGpM3kUOmrxk+GK8D9FPsdUMXxzW0YFUEs/U+X9qaqgopXOKLcgFFc6yc3uI3mg/GITwY1Hc0OhqCe233tc6+PcBmOaA0xNjMNQTXUH3RxKehUZUbRZuozwYyuChZCCBk1XxyaYHM5gjUOSJCGlQkOrjPjLXk78b/OYpGOnSin6jRT4JDFhJt5sK2yHUdePTnfbvAGlONYObXseqiic4f6B7Ca1LIEoY4zKQ6Gw4IIEDawqy2aYsIvqu1lUtbv9//co5r5hEHDL1+jjwGGoV6ylrEOQ+sM/sahJRgsURSicAwfrUdPsc9Y47eyT75Hc19noDnVbqTH3N/9TpdRW3mTegavrZ8t1dyFopVz60o/b8vsmX06GNmZuz7R/SkE=
  template:
    metadata:
      creationTimestamp: null
      name: github-credentials
      namespace: iati-production
    type: kubernetes.io/dockerconfigjson

