apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iati-pv-claim
  labels:
    tier: backend
    layer: fpm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
