<?php

return [
    'add_a_title_and_identifier_for_the_activity'                                       => 'Ajouter un titre et un identifiant pour l\'activité',
    'a_code_specifying_the_language_of_text_in_this_element'                            => 'Des titres dans d\'autres langues peuvent être ajoutés après la création de l\'activité.',
    'a_globally_unique_identifier_for_the_activity'                                     => 'Un identifiant unique pour l\'activité. Une fois qu\'une activité de l\'IITA a été publiée, son identifiant ne peut pas changer dans les mises à jour ultérieures.',
    'type_activity_identifier_here'                                                     => 'Saisir l\'identifiant ici',
    'enter_your_own_unique_activity_identifier_such_as_abbreviation_or_simply_a_number' => 'Saisissez une chaîne de caractères, telle qu\'une abréviation ou un numéro, pour identifier cette activité de manière unique. IATI Publisher combinera cet identifiant avec celui de votre organisation pour créer l\'identifiant de cette activité (\'iati-identifier\').',
    'this_is_autogenerated'                                                             => 'Il est généré automatiquement.',
];
