apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: iati-prod-cert
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: server@yipl.com.np
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: traefik
