name: Tests

on:
  push:
  pull_request:

jobs:
  codecoverage:
      name: Clover test coverage check
      uses: johanvanhelden/gha-clover-test-coverage-check@v1
      with:
        percentage: "95"
        filename: "coverage.xml"
